### ISSUE TITLE
errore

### ISSUE THREAD

**Issue by sefirothmorpheus** [Leone25/hoepli-demo-downloader#1]
ciao
quando eseguo "node index.js" dalla cartella dove ho estratto la repo, mi da il seguente errore:

![error](https://github.com/Leone25/hoepli-demo-downloader/assets/156643499/941399c8-bf03-4bfb-b835-c890c9faf440)

**Comment by Leone25** [comment]
É un errore assai strano, mai visto prima...

Che versione di node.js usi? Prova ad eseguire il comando `node -v`

**Comment by sefirothmorpheus** [comment]
v13.14.0, sono su windows 7, è l'ultima versione che funziona per windows 7
sul mio con windows 10 non posso installare node.js (è un laptop aziendale)

**Comment by Leone25** [comment]
hm, probabilmente allora è quello il problema

puoi provare ad usare una macchina virtuale o ad avviare linux da una chiavette usb
